# Generated by Django 5.2.7 on 2025-11-24 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('image', models.FileField(upload_to='static/images/produits')),
                ('description', models.CharField(max_length=255)),
            ],
        ),
    ]
